spring:
  application:
    name: streamsprocessor
  kafka:
    streams:
      application-id: streams-service
      bootstrap-servers: localhost:29092
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde


