spring:
  application:
      name: Alert Service
  config:
    import: optional:file:.env[.properties]
  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      group-id: alert-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            value:
              default:
                type: com.telemetry.alert.model.Alert
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBIT_USER}
    password: ${RABBIT_PASS}